### ISSUE TITLE
 TODO

### ISSUE THREAD

**Issue by ta1m1kam** [TaigaMikami/FoodieDB#1]
## バックエンド
- [x] ユーザーアイコン画像 の投稿機能
- [x] ユーザーと投稿の紐付け
- [x] ログイン・ログアウト機能
- [x] 画像投稿機能
- [x] いいね機能
- [x] self-assesment for food ★★★★☆

## フロントエンド 
- [x] カードっぽい感じ

**Comment by TaigaMikami** [comment]
#追加
## バックエンド
- [ ] Google Map API 使用して Map表示
- [ ] できれば食べ物関連のWeb APIを使用する

## フロントエンド
- [ ] self-assesment for food ★★★★☆

**Comment by TaigaMikami** [comment]
- [ ] AWS S3で画像保存できるようにしなければ。。。
